name: PR Title Convention Check

on:
  pull_request:
    types: [opened, edited, synchronize]
  workflow_call:
    inputs:
      pr-title:
        required: true
        type: string
      pr-number:
        required: true
        type: string

permissions:
  pull-requests: read
  contents: read

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR title format
        id: check_title
        run: |
          # Use input if called via workflow_call, otherwise use PR event
          if [ "${{ github.event_name }}" = "workflow_call" ]; then
            PR_TITLE="${{ inputs.pr-title }}"
          else
            PR_TITLE="${{ github.event.pull_request.title }}"
          fi
          echo "PR Title: $PR_TITLE"
          
          # Check if title follows conventional commit format
          if echo "$PR_TITLE" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|chore|ci|build)(\(.+\))?(!)?: .+"; then
            echo "✅ PR title follows conventional commit format"
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "❌ PR title does not follow conventional commit format"
            echo "valid=false" >> $GITHUB_OUTPUT
            
            echo ""
            echo "Expected format:"
            echo "  <type>[optional scope]: <description>"
            echo ""
            echo "Valid types:"
            echo "  feat:     A new feature"
            echo "  fix:      A bug fix"
            echo "  docs:     Documentation only changes"
            echo "  style:    Changes that do not affect the meaning of the code"
            echo "  refactor: A code change that neither fixes a bug nor adds a feature"
            echo "  perf:     A code change that improves performance"
            echo "  test:     Adding missing tests or correcting existing tests"
            echo "  chore:    Changes to the build process or auxiliary tools"
            echo "  ci:       Changes to CI configuration files and scripts"
            echo "  build:    Changes that affect the build system or external dependencies"
            echo ""
            echo "Examples:"
            echo "  feat: add user authentication"
            echo "  fix: resolve memory leak in data processing"
            echo "  feat(api): add new endpoint for user management"
            echo "  fix!: breaking change in authentication flow"
            echo ""
            echo "For breaking changes, add ! after the type:"
            echo "  feat!: redesign API with new response format"
          fi

      - name: Fail if title is invalid
        if: steps.check_title.outputs.valid == 'false'
        run: |
          echo "::error::PR title must follow conventional commit format"
          exit 1

      - name: Success message
        if: steps.check_title.outputs.valid == 'true'
        run: |
          echo "✅ PR title validation passed!"
          echo "This PR title follows the conventional commit format and will trigger appropriate version bumping when merged."
