name: PR Title Convention Check

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR title format
        id: check_title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"
          
          # Check if title follows conventional commit format
          if echo "$PR_TITLE" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|chore|ci|build)(\(.+\))?(!)?: .+"; then
            echo "✅ PR title follows conventional commit format"
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "❌ PR title does not follow conventional commit format"
            echo "valid=false" >> $GITHUB_OUTPUT
            
            echo ""
            echo "Expected format:"
            echo "  <type>[optional scope]: <description>"
            echo ""
            echo "Valid types:"
            echo "  feat:     A new feature"
            echo "  fix:      A bug fix"
            echo "  docs:     Documentation only changes"
            echo "  style:    Changes that do not affect the meaning of the code"
            echo "  refactor: A code change that neither fixes a bug nor adds a feature"
            echo "  perf:     A code change that improves performance"
            echo "  test:     Adding missing tests or correcting existing tests"
            echo "  chore:    Changes to the build process or auxiliary tools"
            echo "  ci:       Changes to CI configuration files and scripts"
            echo "  build:    Changes that affect the build system or external dependencies"
            echo ""
            echo "Examples:"
            echo "  feat: add user authentication"
            echo "  fix: resolve memory leak in data processing"
            echo "  feat(api): add new endpoint for user management"
            echo "  fix!: breaking change in authentication flow"
            echo ""
            echo "For breaking changes, add ! after the type:"
            echo "  feat!: redesign API with new response format"
          fi

      - name: Fail if title is invalid
        if: steps.check_title.outputs.valid == 'false'
        run: |
          echo "::error::PR title must follow conventional commit format"
          exit 1

      - name: Comment on PR with validation result
        if: steps.check_title.outputs.valid == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            // Check if we already commented
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('✅ PR title follows conventional commit format')
            );
            
            if (!botComment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: '✅ **PR Title Check Passed**\n\nThis PR title follows the conventional commit format and will trigger appropriate version bumping when merged.'
              });
            }
