name: Required Version Bump

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

permissions:
  contents: write
  pull-requests: read

jobs:
  version-bump-check:
    uses: dedasp/github-config/.github/workflows/version-bump.yml@master
    with:
      commit-message: ${{ github.event.head_commit.message }}
      repository: ${{ github.repository }}
    secrets: inherit
