name: Required Version Bump

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  version-bump-check:
    uses: dedasp/github-config/.github/workflows/version-bump.yml@main
    with:
      commit-message: ${{ github.event.head_commit.message }}
      repository: ${{ github.repository }}
    secrets: inherit
