name: Version Bump

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

permissions:
  contents: write
  pull-requests: read

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get latest tag
        id: get_tag
        run: |
          # Check if any tags exist
          if git describe --tags --abbrev=0 >/dev/null 2>&1; then
            LATEST_TAG=$(git describe --tags --abbrev=0)
            echo "has_tags=true" >> $GITHUB_OUTPUT
            echo "Latest tag: $LATEST_TAG"
          else
            LATEST_TAG="v0.0.0"
            echo "has_tags=false" >> $GITHUB_OUTPUT
            echo "No tags found, starting from v0.0.0"
          fi
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Get PR information
        id: get_pr_info
        uses: actions/github-script@v7
        with:
          script: |
            // Get the latest commit
            const { data: commits } = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            
            const latestCommit = commits[0];
            console.log('Latest commit:', latestCommit.commit.message);
            
            // Try to find associated PR
            let prTitle = null;
            let prNumber = null;
            
            // Check if this is a merge commit
            if (latestCommit.commit.message.includes('Merge pull request')) {
              const prMatch = latestCommit.commit.message.match(/Merge pull request #(\d+)/);
              if (prMatch) {
                prNumber = prMatch[1];
                try {
                  const { data: pr } = await github.rest.pulls.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: prNumber
                  });
                  prTitle = pr.title;
                  console.log(`Found PR #${prNumber}: ${prTitle}`);
                } catch (error) {
                  console.log('Could not fetch PR details:', error.message);
                }
              }
            }
            
            // If no PR found, use commit message
            if (!prTitle) {
              prTitle = latestCommit.commit.message.split('\n')[0]; // First line only
              console.log('Using commit message as title:', prTitle);
            }
            
            core.setOutput('prTitle', prTitle);
            core.setOutput('prNumber', prNumber);

      - name: Analyze PR title
        id: analyze_commits
        run: |
          LATEST_TAG="${{ steps.get_tag.outputs.latest_tag }}"
          HAS_TAGS="${{ steps.get_tag.outputs.has_tags }}"
          
          # Get the PR title from the previous step
          PR_TITLE="${{ steps.get_pr_info.outputs.prTitle }}"
          
          echo "PR title analyzed: $PR_TITLE"
          
          # Determine version bump type based on conventional commit format in PR title
          MAJOR_BUMP=false
          MINOR_BUMP=false
          PATCH_BUMP=false
          
          # Check for breaking changes (major version bump)
          if echo "$PR_TITLE" | grep -qE "^(feat|fix|perf|refactor)(\(.+\))?!:|BREAKING CHANGE:"; then
            MAJOR_BUMP=true
            echo "Breaking change detected - major version bump"
          # Check for new features (minor version bump)
          elif echo "$PR_TITLE" | grep -qE "^feat(\(.+\))?:"; then
            MINOR_BUMP=true
            echo "New feature detected - minor version bump"
          # Check for bug fixes, patches, or other changes (patch version bump)
          elif echo "$PR_TITLE" | grep -qE "^(fix|perf|refactor|docs|style|test|chore|ci|build)(\(.+\))?:"; then
            PATCH_BUMP=true
            echo "Bug fix or patch detected - patch version bump"
          else
            echo "No conventional commit format found in PR title"
            echo ""
            echo "PR title analyzed: $PR_TITLE"
            echo ""
            echo "To create a version tag, use conventional commit format in PR title:"
            echo "  feat: add new feature"
            echo "  fix: resolve bug"
            echo "  docs: update documentation"
            echo ""
            
            # Check if this is a repository with no tags (first version)
            if [ "${{ steps.get_tag.outputs.has_tags }}" = "false" ]; then
              echo "No existing tags found - creating initial version v0.1.0"
              MINOR_BUMP=true
              echo "minor_bump=true" >> $GITHUB_OUTPUT
            else
              echo "Skipping version bump - use conventional commit format in PR title"
              echo "skip_bump=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi
          
          echo "major_bump=$MAJOR_BUMP" >> $GITHUB_OUTPUT
          echo "minor_bump=$MINOR_BUMP" >> $GITHUB_OUTPUT
          echo "patch_bump=$PATCH_BUMP" >> $GITHUB_OUTPUT
          echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT

      - name: Calculate new version
        id: calculate_version
        if: steps.analyze_commits.outputs.skip_bump != 'true'
        run: |
          LATEST_TAG="${{ steps.get_tag.outputs.latest_tag }}"
          
          # Extract version numbers (remove 'v' prefix)
          VERSION=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          # Increment version based on bump type
          if [ "${{ steps.analyze_commits.outputs.major_bump }}" = "true" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "${{ steps.analyze_commits.outputs.minor_bump }}" = "true" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [ "${{ steps.analyze_commits.outputs.patch_bump }}" = "true" ]; then
            PATCH=$((PATCH + 1))
          fi
          
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Create and push tag
        if: steps.analyze_commits.outputs.skip_bump != 'true'
        run: |
          NEW_VERSION="${{ steps.calculate_version.outputs.new_version }}"
          
          # Create the tag
          git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
          
          # Push the tag
          git push origin "$NEW_VERSION"
          
          echo "Created and pushed tag: $NEW_VERSION"

      - name: Create Release
        if: steps.analyze_commits.outputs.skip_bump != 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.calculate_version.outputs.new_version }}
          release_name: Release ${{ steps.calculate_version.outputs.new_version }}
          body: |
            ## Changes in this release
            
            ### PR Title Analyzed:
            ${{ steps.analyze_commits.outputs.pr_title }}
            
            ### Version Bump Type
            ${{ steps.analyze_commits.outputs.major_bump == 'true' && 'Major (breaking changes)' || steps.analyze_commits.outputs.minor_bump == 'true' && 'Minor (new features)' || 'Patch (bug fixes and improvements)' }}
          draft: false
          prerelease: false
